# Source Generated with Decompyle++
# File: media_library_helpers.pyc (Python 3.13)

from __future__ import annotations
import json
import os
import re
from pathlib import Path
from app.api.settings_helpers import read_env_file, set_env_values
SUBTITLE_EXTS = {
    '.ass',
    '.sbv',
    '.srt',
    '.ssa',
    '.sub',
    '.sup',
    '.vtt'}
VIDEO_EXTS = {
    '.ts',
    '.avi',
    '.flv',
    '.m4v',
    '.mkv',
    '.mov',
    '.mp4',
    '.mpg',
    '.wmv',
    '.mpeg',
    '.webm'}
UNCENSORED_STUDIOS = {
    'IP',
    'n1',
    '30s',
    'd3s',
    'fc2',
    'hot',
    'kbn',
    'mow',
    '10mu',
    'heck',
    'ichi',
    'HEYZO',
    'black',
    'carib',
    'ebony',
    'freak',
    'geino',
    'heyzo',
    'n0598',
    'n0599',
    'shame',
    'ArFORD',
    'arford',
    'daijin',
    'empire',
    'fc2ppv',
    'geinou',
    'hikari',
    'kaater',
    'nozoki',
    'rocket',
    'honmono',
    'ippondo',
    'ipponga',
    's2media',
    '10musume',
    'pacopaco',
    'tokyohot',
    'unedited',
    'caribbean',
    'shameless',
    'supercard',
    'tokyohotn',
    'untouched',
    'uncensored',
    'SUPERSTUDIO',
    'bangbrokers',
    'empiremedia',
    'caribbeancom',
    'd伞',
    '|-|鹰',
    '一本',
    '大臣',
    '无忌',
    '无码',
    '热狼',
    '無碼',
    '光date',
    '30多岁',
    '一本画',
    '一本道',
    '东京热',
    '加勒比',
    '無修正',
    'd伞 Studios',
    '天然素材',
    '番号商店',
    '自然资源',
    'エンパイア',
    'カリビアン',
    'パコパコ団',
    'ステージ2メディア',
    'mow-av',
    'fc2-ppv',
    's2-media',
    'rocket-ch',
    'tokyo-hot'}
UNCENSORED_PATH_KEYWORDS = {
    'n1',
    'fc2',
    '10mu',
    'toph',
    'unco',
    'carib',
    'heyzo',
    'n0598',
    'n0599',
    'n0842',
    'n0843',
    'n1pon',
    'saika',
    'blacked',
    '10musume',
    'uncensored',
    '无码',
    '流出',
    '無碼',
    '無修正',
    'カリビアン',
    'saika-',
    'tokyo-hot'}
ADAPTER_NOT_ACTIVATED = '媒体库适配器未配置，请在设置中配置 Emby / Jellyfin 服务器地址'
MEDIA_LIBRARY_SCAN_GROUPS_ENV = 'MEDIA_LIBRARY_SCAN_GROUPS'
MEDIA_LIBRARY_PATH_PREFIX_ENV = 'MEDIA_LIBRARY_PATH_PREFIX'
MEDIA_LIBRARY_LOCAL_PATH_PREFIX_ENV = 'MEDIA_LIBRARY_LOCAL_PATH_PREFIX'
# WARNING: Decompyle incomplete
