export const zh: Record<string, string> = {
  // 通用
  'common.save': '保存',
  'common.cancel': '取消',
  'common.delete': '删除',
  'common.close': '关闭',
  'common.loading': '加载中...',
  'common.confirm': '确认',
  'common.search': '搜索',
  'common.refresh': '刷新',
  'common.download': '下载',
  'common.test': '测试',
  'common.success': '成功',
  'common.error': '错误',
  'common.warning': '警告',

  // 导航
  'nav.overview': '概览',
  'nav.library': '媒体库',
  'nav.jobs': '任务',
  'nav.history': '历史',
  'nav.settings': '设置',

  // Toolbar
  'toolbar.blurOn': '开启封面模糊',
  'toolbar.blurOff': '关闭封面模糊',
  'toolbar.switchLang': '切换语言',
  'toolbar.collapse': '收起',

  // Home/Library
  'library.title': '媒体库',
  'library.search.placeholder': '搜索标题...',
  'library.filter.all': '全部',
  'library.filter.uncensored': '无码',
  'library.filter.chinese': '中文',
  'library.filter.leaked': '流出',
  'library.filter.anal': '肛交',
  'library.filter.破解': '破解',
  'library.noResults': '未找到结果',
  'library.itemsPerPage': '每页',
  'library.loadMore': '加载更多',

  // Whisper dropdown options
  'whisper.model.animeWhisper': 'Anime-Whisper (推荐JAV)',
  'whisper.model.largeV3': 'Faster-Whisper Large v3',
  'whisper.model.largeV3Turbo': 'Faster-Whisper Large v3 Turbo',
  'whisper.model.medium': 'Faster-Whisper Medium',
  'whisper.model.small': 'Faster-Whisper Small',
  'whisper.model.base': 'Faster-Whisper Base',
  'whisper.model.tiny': 'Faster-Whisper Tiny',
  'whisper.pipeline.ensemble': '两遍处理 + 智能合并 (推荐)',
  'whisper.pipeline.single': '单遍处理',
  'whisper.merge.smartMerge': '智能合并 (推荐)',
  'whisper.merge.fullMerge': '合并所有',
  'whisper.merge.pass1Primary': 'Pass1 为主',
  'whisper.merge.pass2Primary': 'Pass2 为主',
  'whisper.merge.longest': '选择最长文本',
  'whisper.lang.ja': '日语',
  'whisper.lang.auto': '自动检测',
  'whisper.lang.en': '英语',
  'whisper.lang.zh': '中文',
  'whisper.sensitivity.conservative': '保守 (减少误识别)',
  'whisper.sensitivity.balanced': '平衡 (推荐)',
  'whisper.sensitivity.aggressive': '激进 (更多检测)',

  // MediaCard
  'mediacard.chinese': '中字',
  'mediacard.cracked': '已破',
  'mediacard.crack': '破解',
  'mediacard.noCover': 'NO COVER',

  // 详情弹窗
  'detail.submitTask': '提交任务',
  'detail.viewDetails': '查看详情',
  'detail.actors': '演员',
  'detail.genres': '类型',
  'detail.director': '导演',
  'detail.duration': '时长',
  'detail.year': '年份',
  'detail.studio': '片商',
  'detail.unwatched': '未看',
  'detail.watched': '已看',
  'detail.quickCrack': '快速破解',
  'detail.selectSubtitle': '选择字幕',
  'detail.noSubtitles': '暂无字幕',
  'detail.downloadSubtitle': '下载字幕',

  // 字幕
  'subtitle.local': '本地字幕',
  'subtitle.online': '在线搜索',
  'subtitle.whisper': 'Whisper AI',
  'subtitle.preview': '预览',
  'subtitle.download': '下载',
  'subtitle.search.placeholder': '输入车牌搜索...',
  'subtitle.search': '搜索',
  'subtitle.noResults': '未找到字幕',
  'subtitle.rescan': '重新搜索',
  'subtitle.source': '来源',
  'subtitle.downloadSuccess': '字幕下载成功',
  'subtitle.downloadError': '字幕下载失败',

  // Whisper AI
  'whisper.title': 'Whisper AI 字幕生成',
  'whisper.model': '模型',
  'whisper.pipeline': '管道模式',
  'whisper.mergeStrategy': '合并策略',
  'whisper.mergeStrategy.smart': '智能合并',
  'whisper.mergeStrategy.none': '不合并',
  'whisper.mergeStrategy.strict': '严格合并',
  'whisper.mergeStrategy.loose': '宽松合并',
  'whisper.language': '语言',
  'whisper.sensitivity': '敏感度',
  'whisper.start': '开始生成',
  'whisper.running': '生成中...',
  'whisper.selectModel': '请先在设置中选择模型',

  // Jobs
  'jobs.title': '任务',
  'jobs.current': '当前任务',
  'jobs.noRunning': '暂无运行中或排队的任务',
  'jobs.logs': '日志',
  'jobs.clickForLogs': '点击任务查看日志',
  'jobs.recent': '最近任务',
  'jobs.cancel': '取消',
  'jobs.queued': '排队中',
  'jobs.cleanup': '清理孤立任务',
  'jobs.cleanup.done': '已清理 {n} 个孤立任务',
  'jobs.cleanup.none': '没有需要清理的孤立任务',
  'jobs.cancelConfirm': '确认取消此任务？',
  'jobs.running': '进行中',
  'jobs.cancelTask': '取消任务',
  'jobs.emptyTitle': '暂无任务',
  'jobs.logsTitle': '实时日志',

  // History
  'history.title': '历史记录',
  'history.filter.all': '全部',
  'history.filter.completed': '已完成',
  'history.filter.failed': '失败',
  'history.noHistory': '暂无历史记录',
  'history.col.name': '名称',
  'history.col.status': '状态',
  'history.col.created': '创建时间',
  'history.col.completed': '完成时间',
  'history.col.output': '输出',
  'history.col.actions': '操作',
  'history.col.progress': '进度',
  'history.recordCount': '共 {n} 条记录',
  'history.unknownJob': '未知任务',
  'history.deleteConfirm': '确认删除此记录？',

  // Settings
  'settings.title': '设置',
  'settings.tab.system': '系统',
  'settings.tab.storage': '存储',
  'settings.tab.lada': 'LADA',
  'settings.tab.whisper': 'Whisper',
  'settings.emby.title': 'Emby 连接',
  'settings.emby.server': '服务器地址',
  'settings.emby.apiKey': 'API 密钥',
  'settings.emby.userId': '用户 ID',
  'settings.emby.userIdPlaceholder': 'Emby 用户 ID (可在 Emby Web URL 或 用户设置中找到)',
  'settings.emby.testConnection': '测试连接',
  'settings.emby.selectLibrary': '显示媒体库',
  'settings.emby.selectLibraryHint': '选择要显示的媒体库（留空显示全部）',
  'settings.emby.selectedLibs': '已选择: {libs}',
  'settings.emby.all': '全部',
  'settings.emby.connected': '已连接到 {name}',
  'settings.emby.connectFailed': '连接失败：{error}',
  'settings.emby.loadFailed': '加载设置失败',
  'settings.emby.forMediaDetails': '用于获取媒体详情',
  'settings.network.title': '网络加速',
  'settings.network.mode': '加速方式',
  'settings.network.mode.none': '无（直连）',
  'settings.network.mode.proxy': 'HTTP 代理 (如 http://127.0.0.1:7890)',
  'settings.network.mode.mirror': '国内镜像 (GitHub + HF + pip)',
  'settings.network.proxy': '代理地址',
  'settings.network.proxyHint': '用于 Git 克隆和所有下载',
  'settings.network.noneHint': '无加速，直连访问',
  'settings.network.proxyHint2': '使用 HTTP 代理进行所有下载',
  'settings.network.mirrorHint': '使用 ghproxy.com (GitHub)、hf-mirror.com (HuggingFace)、清华 pip 镜像',
  'settings.network.githubMirror': 'GitHub 镜像',
  'settings.network.hfMirror': 'HuggingFace 镜像',
  'settings.network.pipMirror': 'pip 镜像',
  'settings.storage.title': '存储路径',
  'settings.storage.source': '源目录',
  'settings.storage.sourceHint': 'Emby 媒体目录（硬链接文件存储位置）',
  'settings.storage.output': '输出目录',
  'settings.storage.outputHint': 'LADA 输出保存位置（.restored-u.mp4）— 默认跟随源目录',
  'settings.storage.whisperModelDir': 'Whisper 模型目录',
  'settings.storage.whisperModelDirHint': 'Whisper 模型自定义目录（留空使用默认）',
  'settings.storage.ladaModelDir': 'LADA 模型目录',
  'settings.storage.ladaModelDirHint': 'LADA AI 模型自定义目录（留空使用默认）',
  'settings.storage.browse': '浏览',
  'settings.storage.save': '保存',
  'settings.storage.loadFailed': '加载设置失败',
  'settings.storage.saveFailed': '保存失败',
  'settings.storage.loading': '加载中...',
  'settings.dirPicker.parentDir': '上级目录',
  'settings.dirPicker.loading': '加载中...',
  'settings.dirPicker.emptyDir': '空目录',
  'settings.dirPicker.hint': '双击文件夹进入，确认选择',
  'settings.dirPicker.cancel': '取消',
  'settings.dirPicker.selectFolder': '选择此文件夹',
  'settings.dirPicker.loadDirFailed': '加载目录失败',
  'settings.lada.title': 'LADA 设置',
  'settings.lada.cliPath': 'LADA CLI 路径',
  'settings.lada.version': '版本',
  'settings.lada.versionNotFound': '未找到',
  'settings.lada.docker': 'Docker 模式',
  'settings.lada.runningMode': '运行模式',
  'settings.lada.upgrade': '升级',
  'settings.lada.upgrading': '升级中...',
  'settings.lada.upgradeConfirm': '升级 LADA 到最新版本？',
  'settings.lada.upgradedTo': 'LADA 已升级到 {version}',
  'settings.lada.upgradeFailed': '升级失败',
  'settings.lada.device': '设备',
  'settings.lada.fp16': 'FP16',
  'settings.lada.fp16Enabled': '启用（推荐 - 更快，显存更少）',
  'settings.lada.fp16Disabled': '禁用 (FP32)',
  'settings.lada.detectionModel': '检测模型',
  'settings.lada.restorationModel': '修复模型',
  'settings.lada.encodingPreset': '编码预设',
  'settings.lada.maxClipLength': '最大片段长度（帧）',
  'settings.lada.maxClipLengthHint': '值越高 = 更好的时序稳定性，需要更多显存',
  'settings.lada.detectFaceMosaics': '检测人脸马赛克',
  'settings.lada.detectFaceMosaicsHint': '检测并忽略像素化人脸，可能影响 NSFW 检测',
  'settings.lada.defaultSettings': '默认设置',
  'settings.lada.defaultSettingsHint': '这些设置将作为运行 LADA 修复时的默认值',
  'settings.lada.saveDefaults': '保存默认设置',
  'settings.lada.saving': '保存中...',
  'settings.lada.savePaths': '保存路径',
  'settings.lada.modelWeightsDir': '模型权重目录',
  'settings.lada.modelWeightsDirNotConfigured': '未配置',
  'settings.lada.detectionModels': '检测模型',
  'settings.lada.restorationModels': '修复模型',
  'settings.lada.downloaded': '已下载',
  'settings.lada.notDownloaded': '未下载',
  'settings.lada.refreshing': '刷新中...',
  'settings.lada.refresh': '刷新',
  'settings.lada.detectionModelsNote': '模型需要从 LADA Release 页面下载 (codeberg.org/ladaapp/lada/releases)',
  'settings.lada.restorationModelsNote': '主要修复模型 (~11GB) 必须从 LADA Release 页面下载',
  'settings.lada.cli': 'LADA CLI',
  'settings.lada.modelWeightsDirLabel': '模型权重目录',
  'settings.lada.notDownloadedShort': '未下',
  'settings.lada.loadFailed': '加载设置失败',
  'settings.lada.saveFailed': '保存失败',
  'settings.whisper.title': 'Whisper 设置',
  'settings.whisper.defaultSettings': '默认设置',
  'settings.whisper.defaultSettingsHint': '这些设置将作为从媒体库生成 AI 字幕时的默认值',
  'settings.whisper.model': '模型',
  'settings.whisper.pipelineMode': 'Pipeline 模式',
  'settings.whisper.mergeStrategy': '合并策略',
  'settings.whisper.language': '语言',
  'settings.whisper.sensitivity': '灵敏度',
  'settings.whisper.dependencies': '依赖',
  'settings.whisper.models': '模型',
  'settings.whisper.checkFailed': '检查依赖失败',
  'settings.whisper.saveFailed': '保存失败',
  'settings.whisper.whisperSettingsSaved': 'Whisper 设置已保存',
  'settings.whisper.installDeps': '安装依赖',
  'settings.whisper.installDepsConfirm': '安装 Whisper 依赖 (torch, transformers, faster-whisper)?',
  'settings.whisper.installing': '安装中...',
  'settings.whisper.installSuccess': '依赖安装成功',
  'settings.whisper.installFailed': '安装失败',
  'settings.whisper.downloadModel': '下载模型',
  'settings.whisper.downloadModelConfirm': '下载模型 {modelId}?',
  'settings.whisper.downloading': '开始下载...',
  'settings.whisper.downloadSuccess': '模型下载成功',
  'settings.whisper.downloadFailed': '下载失败',
  'settings.whisper.deleteModel': '删除模型',
  'settings.whisper.deleteModelConfirm': '删除模型 {modelId}?',
  'settings.whisper.deleted': '模型已删除',
  'settings.whisper.deleteFailed': '删除失败',
  'settings.whisper.refreshing': '刷新中...',
  'settings.whisper.refresh': '刷新',
  'settings.whisper.download': '下载',
  'settings.whisper.installed': '已安装',
  'settings.whisper.notInstalled': '未安装',
  'settings.whisper.installingShort': '安装中...',
  'settings.whisper.cpuOnly': '仅 CPU',
  'settings.whisper.gpuAvailable': 'GPU 可用',
  'settings.whisper.cuda': 'CUDA (GPU)',
  'settings.whisper.saving': '保存中...',
  'settings.whisper.saveDefaults': '保存默认设置',
  'settings.whisper.sensitivityConservative': '保守',
  'settings.whisper.sensitivityBalanced': '均衡',
  'settings.whisper.sensitivityAggressive': '激进',
  'settings.whisper.defaults': '默认设置',
  'settings.whisper.checkDeps': '检测依赖',
  'settings.whisper.downloadModel': '下载模型',
  'settings.whisper.deleteModel': '删除',
  'settings.whisper.installing': '安装中...',
  'settings.saveSuccess': '设置已保存',
  'settings.saveFailed': '保存失败：{error}',
  'settings.saveNetwork': '网络设置已保存',
  'settings.saveNetworkFailed': '保存网络设置失败',
  'settings.loading': '加载中...',
  'settings.saving': '保存中...',
  'settings.ui.blur': '封面模糊',
  'settings.ui.blurHint': '媒体库封面默认添加模糊保护，点击工具栏眼睛图标可快速切换',
  'settings.ui.blurEnabled': '已开启',
  'settings.ui.blurDisabled': '已关闭',

  // Dashboard
  'dashboard.welcome.message': '很高兴再次见到你！\n系统运行一切正常。',
  'dashboard.welcome.greeting': '欢迎回来,',
  'dashboard.welcome.voiceAssistant': '语音助手',
  'dashboard.stats.total': '全部',
  'dashboard.stats.cracked': '已破',
  'dashboard.stats.chinese': '中字',
  'dashboard.stats.leaked': '流出',
  'dashboard.stats.uncensored': '无码',
  'dashboard.gpu.title': 'GPU 状态',
  'dashboard.gpu.util': 'GPU 利用率',
  'dashboard.gpu.memory': '显存使用',
  'dashboard.gpu.temp': 'GPU 温度',
  'dashboard.gpu.power': '功耗',
  'dashboard.cpu.title': 'CPU & 内存',
  'dashboard.cpu.util': 'CPU 利用率',
  'dashboard.cpu.memory': '内存使用',
  'dashboard.cpu.temp': 'CPU 温度',
  'dashboard.cpu.disk': '磁盘读取',
  'dashboard.recentJobs': '最近任务',
  'dashboard.viewAll': '查看全部 →',
  'dashboard.noJobs': '暂无任务记录',
  'dashboard.job.completed': '完成',
  'dashboard.job.running': '运行中',
  'dashboard.job.failed': '失败',
  'dashboard.job.queued': '排队中',
  'dashboard.justNow': '刚刚',
  'dashboard.minsAgo': '{n} 分钟前',
  'dashboard.hoursAgo': '{n} 小时前',
  'dashboard.unknown': 'Unknown',
  'dashboard.user': '用户',

  // 连接状态
  'status.connected': '已连接',
  'status.disconnected': '未连接',
  'status.connecting': '连接中...',
}
